name: Mirror lei0308/mirror-test to huanglei0308/mirror-test

on:
  pull_request:
    branches: [master]
    paths:
      - '.github/workflows/**'
  schedule:
    - cron: '0 1/2 * * *'
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    env:
      PIP_BREAK_SYSTEM_PACKAGES: "1"
    
    steps:
      - name: Mirror GitCode to GitHub
        uses: Yikun/hub-mirror-action@v1.3
        with:
          src: gitcode/lei0308
          dst: github/huanglei0308
          dst_key: ${{ secrets.GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.GITHUB_TOKEN }}
          account_type: user
          clone_style: ssh
          force_update: true
          debug: true
          static_list: "mirror-test"
